### ISSUE TITLE
help me running this

### ISSUE THREAD

**Issue by MrTimonM** [Widiskel/midas-RWA-bot#5]
![Screenshot_9](https://github.com/user-attachments/assets/74542cb7-aa52-447e-b043-311d9de9df3a)
hi, can you please help me running this 

I am getting this error -
`
Please Choose a menu:

1. Create Account
2. Reset Account
3. Start Bot
4. Query modification

Input your choice : 3
Error During executing bot Error: A file exists at the location 'D:\midas-RWA-bot-master\accounts\AR67.session' when trying to create/open localStorage
    at LocalStorage._init (D:\midas-RWA-bot-master\node_modules\node-localstorage\LocalStorage.js:159:17)
    at new LocalStorage (D:\midas-RWA-bot-master\node_modules\node-localstorage\LocalStorage.js:124:12)
    at new StoreSession (D:\midas-RWA-bot-master\node_modules\telegram\sessions\StoreSession.js:18:61)
    at Telegram.useSession (file:///D:/midas-RWA-bot-master/app/src/core/telegram.js:1:8672)
    at file:///D:/midas-RWA-bot-master/app/index.js:1:3989
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
`

**Comment by Widiskel** [comment]
create session using this bot bro. you cannot use different format session except from my bot
